apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bitstamp-exporter
  namespace: bitstamp-exporter
  labels:
    release: prometheus
spec:
  jobLabel: bitstamp-exporter
  selector:
    matchLabels:
      exporter: mystrom
  namespaceSelector:
    matchNames:
      - bitstamp-exporter
  endpoints:
    - port: http-metrics
      interval: 1m
      path: /metrics
